### ISSUE TITLE
No Driver for Pi 4 in 6.1.20 and 5.10.83  for yocto image 64 bit,do you have source code ,I can build it by myself

### ISSUE THREAD

**Issue by gitgonewithwind** [waveshare/Waveshare-DSI-LCD#11]
Hi all,
I use PI4 yocto image .currently the kernel  is 6.1.20 NOT  raspbian image  6.1.21.

I used your driver to test in raspbian image  6.1.21. It worked well.
but I have to use ycoto image for our application. it's hard to change many things to update ycoto to kernel 6.1.21 (I posted my issue here https://github.com/agherzan/meta-raspberrypi/issues/1193 )

I tried to install  6.1.21 drivers in yocto image 6.1.20, but error happened:

Driver Start Settings
..
modprobe: ERROR: could not insert 'WS_xinchDSI_Touch': Exec format error
modprobe: ERROR: could not insert 'WS_xinchDSI_Screen': Exec format error
It already exists and does not need to be added
It already exists and does not need to be added
It already exists and does not need to be added
It already exists and does not need to be added

--
it seems I have to install exactly same version drivers for kernel 6.1.20?
How can I do?
can you build  6.1.20  64bit drivers for me ?
or 
can you build  5.10.83  64bit   drivers ? currently I am using yocto kernel 5.10.83 for our products. but there are no drivers, so I tried to update to  6.1.20, but there is still no driver.   5.10.83  64bit driver  is my best solution so that I do not need to update the whole system apps  to 6.1.20.

Thank you so much.

**Comment by gitgonewithwind** [comment]
I want to know do you support yocto image if the the kernel version is same as raspbian image version 6.1.21?
 nobody reply ?

**Comment by 6by9** [comment]
See the discussion in #4 that resulted in https://github.com/raspberrypi/linux/pull/5433 for an open source driver for these panels.

Waveshare have largely stated in https://github.com/waveshare/Waveshare-DSI-LCD/issues/1#issuecomment-1276965891 that they are only ever going to produce modules for the stable Raspberry Pi OS releases, and source hasn't been forthcoming despite their GPLv2 licence obligations.

**Comment by gitgonewithwind** [comment]
@waveshare @6by9 
for raspberry pi yocto solution is here
https://github.com/agherzan/meta-raspberrypi/issues/1211#issuecomment-1691776270 
close the issue. please.
Thank you

**Comment by 6by9** [comment]
> close the issue. please.

I can't as I'm not an admin on this repo, nor the original author. You should be able to as the original author.
