### ISSUE TITLE
Request driver for Kernel version 6.6.31

### ISSUE THREAD

**Issue by AnshumanFauzdar** [waveshare/Waveshare-DSI-LCD#32]
@waveshare Please update the driver for Kernel version 6.6.31 as per the latest update for Raspberry Pi OS (64-bit) [release notes](https://downloads.raspberrypi.com/raspios_arm64/release_notes.txt)

Display is not usable at all. I can't even VNC into the Pi.

**Comment by StevPem** [comment]
I second this request. We need support for 6.6.31

**Comment by StevPem** [comment]
It seems the default Linux kernel supports multiple Waveshare DSI LCD displays.

You DO NOT need the pre-compiled drivers provided by Waveshare.
Just add the correct dtoverlay lines in the /boot/firmware/config.txt file.

Refer to: https://github.com/raspberrypi/linux/blob/rpi-6.6.y/arch/arm/boot/dts/overlays/README

**Comment by AnshumanFauzdar** [comment]
> It seems the default Linux kernel supports multiple Waveshare DSI LCD models.
> 
> You DO NOT need the pre-compiled drivers provided by Waveshare. Just add the correct dtoverlay lines in the /boot/firmware/config.txt file.
> 
> Refer to: https://github.com/raspberrypi/linux/blob/rpi-6.6.y/arch/arm/boot/dts/overlays/README

I check the config.txt file and following dtoverlay setting is there:
```
ignore_lcd=1
dtparam=i2c_vc=on
dtparam=i2c_arm=on
dtoverlay=WS_xinchDSI_Screen,SCREEN_type=8,I2C_bus=10
dtoverlay=WS_xinchDSI_Touch,I2C_bus=10,invertedx,swappedxy
```
I am assuming that driver package is required for the screen to work for the specific kernel version.
Driver package I am referring to:

```
WS_xinchDSI_Screen.dtbo
WS_xinchDSI_Screen.ko
WS_xinchDSI_Screen_Interface.ko
WS_xinchDSI_Touch.dtbo
WS_xinchDSI_Touch.ko
WS_xinchDSI_Touch_Interface.ko
```

**Comment by StevPem** [comment]
Instructions are here: https://www.waveshare.com/wiki/10.1inch_DSI_LCD_(C)

**Comment by AnshumanFauzdar** [comment]
> Instructions are here: https://www.waveshare.com/wiki/10.1inch_DSI_LCD_(C)

Thanks @StevPem 

Quick instruction for people who are facing the same problem on kernel version 6.6.31:

1.  Remove the following lines from the /boot/firmware/config.txt, in case you have installed drivers for it:
```
ignore_lcd=1
dtparam=i2c_vc=on
dtparam=i2c_arm=on
dtoverlay=WS_xinchDSI_Screen,SCREEN_type=8,I2C_bus=10
dtoverlay=WS_xinchDSI_Touch,I2C_bus=10,invertedx,swappedxy
```
2. Add following at end of config.txt, for more detailed instructions refer to [www.waveshare.com/wiki/10.1inch_DSI_LCD_(C)](https://www.waveshare.com/wiki/10.1inch_DSI_LCD_(C))
```
dtoverlay=vc4-kms-v3d
dtoverlay=vc4-kms-dsi-waveshare-panel,10_1_inch
```
3. Reboot and screen will be working again.
