### ISSUE TITLE
Kernel version 6.1.21 

### ISSUE THREAD

**Issue by deiger** [waveshare/Waveshare-DSI-LCD#8]
Hello,

Raspbian has updated their kernel to 6.1.21 two weeks ago, however the driver is yet to be updated.
Note that even the driver for 6.1.19 is currently available only for 64bit.
That's far more than the 48 hours promised in https://github.com/waveshare/Waveshare-DSI-LCD/issues/1#issuecomment-1276965891.
It seems that tracking the version updates and releasing new drivers doesn't scale well.

Thanks you.

**Comment by mbhangui** [comment]
After kernel update my 7.9 DSI display has stopped working. I find the driver yet to be updated. The drivers fail to load, can you please look into it

```
Apr 11 16:46:53 PI3 kernel: WS_xinchDSI_Screen_Interface: loading out-of-tree module taints kernel.
Apr 11 16:46:53 PI3 kernel: WS_xinchDSI_Screen: module license 'Proprietary' taints kernel.
Apr 11 16:46:53 PI3 kernel: Disabling lock debugging due to kernel taint
Apr 11 16:46:53 PI3 kernel: WS_xinchDSI_Screen: disagrees about version of symbol drm_panel_add
Apr 11 16:46:53 PI3 kernel: WS_xinchDSI_Screen: Unknown symbol drm_panel_add (err -22)
Apr 11 16:46:53 PI3 kernel: WS_xinchDSI_Screen: disagrees about version of symbol drm_panel_remove
Apr 11 16:46:53 PI3 kernel: WS_xinchDSI_Screen: Unknown symbol drm_panel_remove (err -22)
Apr 11 16:46:53 PI3 kernel: WS_xinchDSI_Screen: disagrees about version of symbol drm_panel_init
Apr 11 16:46:53 PI3 kernel: WS_xinchDSI_Screen: Unknown symbol drm_panel_init (err -22)
```

**Comment by petrkra** [comment]
It's a big shame for the manufacturer.  You buy a display and even after a week you can't get it working - the drivers don't exist!  And with the next kernel update, your display will stop working. 
Would it really be such a problem to make drivers independent of the kernel version?

**Comment by deiger** [comment]
Finally an update to 6.1.21 for 64 bit, but still no update for 32 bit...
